agentfs run: Fix nested pwrite() on overlay filesystem
When running `git switch` in an `agentfs run` session, we got the
following error:

```
penberg@turing:~/src/tursodatabase/agentfs$ agentfs run bash
Welcome to AgentFS!

The following directories are writable:

  - /home/penberg/src/tursodatabase/agentfs (copy-on-write)
  - /home/penberg/.claude
  - /home/penberg/.claude.json
  - /home/penberg/.local
  - /home/penberg/.npm

Everything else is read-only.

To join this session from another terminal:

  agentfs run --session be3e8fff-88d0-417d-a3e7-71467320f132 <command>

🤖 penberg@turing:~/src/tursodatabase/agentfs$ git switch main
error: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Input/output error
fatal: unable to update HEAD
```

As it turns out, the issue was that pwrite() was not handling nested
paths correctly in overlay filesystem.